/* Generated By:JJTree: Do not edit this line. ast_num_double.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ast_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

import io.leaderli.litool.core.meta.LiTuple;

public class ast_num_double extends SimpleNode<LiTuple<String, Double>> {
    public ast_num_double(int id) {
        super(id);
    }

    public ast_num_double(RuleParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(RuleParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=b195b9a94baf6d3f4a4f71089cd14610 (do not edit this line) */
