/* Generated By:JJTree: Do not edit this line. ast_entry.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ast_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

public class ast_entry extends SimpleNode<Void> {
    public ast_entry(int id) {
        super(id);
    }

    public ast_entry(RuleParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(RuleParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=113d02a640dfd09ada22b615a3af3793 (do not edit this line) */
