/* Generated By:JJTree: Do not edit this line. ast_num_time.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ast_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

import io.leaderli.litool.core.meta.LiTuple;

public class ast_num_time extends SimpleNode<LiTuple<String, String>> {
    public ast_num_time(int id) {
        super(id);
    }

    public ast_num_time(RuleParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(RuleParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=7b5c1cb3c962fb35e4367e8c9c11d4aa (do not edit this line) */
