/* Generated By:JJTree: Do not edit this line. ast_var.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=ast_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

import io.leaderli.litool.core.meta.LiTuple;

public class ast_var extends SimpleNode<LiTuple<String, String>> {
    public ast_var(int id) {
        super(id);
    }

    public ast_var(RuleParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(RuleParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=7bd3304354d74270e5a2be837947bdbe (do not edit this line) */
