/* Generated By:JJTree: Do not edit this line. ASTdouble_value.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

public class ASTdouble_value extends SimpleNode {
    public ASTdouble_value(int id) {
        super(id);
    }

    public ASTdouble_value(RuleParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public void jjtAccept(RuleParserVisitor visitor, StringBuilder data) {

        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=cf4b6190cb58682c3fb5fa7973c9dbc1 (do not edit this line) */
