/* Generated By:JJTree: Do not edit this line. ASToperator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

public class ASToperator extends SimpleNode {
    public ASToperator(int id) {
        super(id);
    }

    public ASToperator(RuleParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public void jjtAccept(RuleParserVisitor visitor, StringBuilder data) {

        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=85afc7342a85e962aedd0cac8da7962f (do not edit this line) */
