/* Generated By:JJTree: Do not edit this line. ASTpercent_value.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

public class ASTpercent_value extends SimpleNode {
    public ASTpercent_value(int id) {
        super(id);
    }

    public ASTpercent_value(RuleParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public void jjtAccept(RuleParserVisitor visitor, io.leaderli.rule.RuleContext data) {

        visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=0aab6a9ccb82b2e9d4b0fe5fe0b3dc5b (do not edit this line) */
