/* Generated By:JJTree: Do not edit this line. ASTvar.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.leaderli.rule.tree;

public
class ASTvar extends SimpleNode {
  public ASTvar(int id) {
    super(id);
  }

  public ASTvar(RuleParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(RuleParserVisitor visitor, StringBuilder data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=39e50a9dd1e294bee83fb4957b043486 (do not edit this line) */
