/* Generated By:JavaCC: Do not edit this line. RuleParserTreeConstants.java Version 7.0.13 */
package io.leaderli.rule.tree;

public interface RuleParserTreeConstants {
    public int JJTSTART = 0;
    public int JJTRULE = 1;
    public int JJTVOID = 2;
    public int JJTAND = 3;
    public int JJTOR = 4;
    public int JJTTERM = 5;
    public int JJTNEG = 6;
    public int JJTNUM = 7;
    public int JJTSTR = 8;
    public int JJTCOMPARE2 = 9;
    public int JJTTEST = 10;

    public String[] jjtNodeName = { "Start", "rule", "void", "and", "or", "term", "neg", "num", "str", "compare2",
            "test", };
}
/* JavaCC - OriginalChecksum=3cce52b320d2e2af9f3de523b077b7eb (do not edit this line) */
