/* Generated By:JavaCC: Do not edit this line. RuleParserTreeConstants.java Version 7.0.13 */
package io.leaderli.rule.tree;

public interface RuleParserTreeConstants {
    public int JJTSTART = 0;
    public int JJTRULE = 1;
    public int JJTVOID = 2;
    public int JJTAND = 3;
    public int JJTOR = 4;
    public int JJTTERM = 5;
    public int JJTNEG = 6;
    public int JJTNUM_INT = 7;
    public int JJTNUM_DOUBLE = 8;
    public int JJTNUM_PERCENT = 9;
    public int JJTNUM_TIME = 10;
    public int JJTCOMPARE = 11;
    public int JJTMATH = 12;
    public int JJTOPERATOR = 13;
    public int JJTVAR = 14;
    public int JJTTEST = 15;

    public String[] jjtNodeName = { "Start", "rule", "void", "and", "or", "term", "neg", "num_int", "num_double",
            "num_percent", "num_time", "compare", "math", "operator", "var", "test", };
}
/* JavaCC - OriginalChecksum=60e507b7d1a1539fc3bc1d38db61f88a (do not edit this line) */
