/* Generated By:JavaCC: Do not edit this line. RuleParserTreeConstants.java Version 7.0.13 */
package io.leaderli.rule.tree;

public interface RuleParserTreeConstants {
    public int JJTSTART = 0;
    public int JJTRULE = 1;
    public int JJTVOID = 2;
    public int JJTAND = 3;
    public int JJTOR = 4;
    public int JJTTERM = 5;
    public int JJTNEG = 6;
    public int JJTNUM = 7;
    public int JJTCOMPARE = 8;
    public int JJTOPERATOR = 9;
    public int JJTVAR = 10;
    public int JJTTEST = 11;

    public String[] jjtNodeName = { "Start", "rule", "void", "and", "or", "term", "neg", "num", "compare", "operator",
            "var", "test", };
}
/* JavaCC - OriginalChecksum=97daf42e1c3080000a0144215b867487 (do not edit this line) */
