/* Generated By:JavaCC: Do not edit this line. RuleParserVisitor.java Version 7.0.13 */
package io.leaderli.rule.tree;

public interface RuleParserVisitor {
    public void visit(SimpleNode node, StringBuilder data);

    public void visit(ASTStart node, StringBuilder data);

    public void visit(ASTrule node, StringBuilder data);

    public void visit(ASTand node, StringBuilder data);

    public void visit(ASTor node, StringBuilder data);

    public void visit(ASTterm node, StringBuilder data);

    public void visit(ASTneg node, StringBuilder data);

    public void visit(ASTtime_value node, StringBuilder data);

    public void visit(ASTint_value node, StringBuilder data);

    public void visit(ASTdouble_value node, StringBuilder data);

    public void visit(ASTpercent_value node, StringBuilder data);

    public void visit(ASTcompare node, StringBuilder data);

    public void visit(ASToperator node, StringBuilder data);

    public void visit(ASTstr_operator node, StringBuilder data);

    public void visit(ASTvar node, StringBuilder data);

    public void visit(ASTtest node, StringBuilder data);
}
/* JavaCC - OriginalChecksum=065337774c761b2d7eca8eb59afbdbdd (do not edit this line) */
