/* Generated By:JavaCC: Do not edit this line. RuleParserDefaultVisitor.java Version 7.0.13 */
package io.leaderli.rule.tree;

public class RuleParserDefaultVisitor implements RuleParserVisitor {
    public void defaultVisit(SimpleNode node, StringBuilder data) {
        node.childrenAccept(this, data);
        return;
    }

    public void visit(SimpleNode node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTStart node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTnum node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTvar node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTtest node, StringBuilder data) {
        defaultVisit(node, data);
    }
}
/* JavaCC - OriginalChecksum=853ac1e1e8479fbe2ffcb0aca3b5cfa0 (do not edit this line) */
