/* Generated By:JJTree&JavaCC: Do not edit this line. RuleParserConstants.java */
package io.leaderli.rule.tree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RuleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TYPE = 2;
  /** RegularExpression Id. */
  int NAME = 3;
  /** RegularExpression Id. */
  int SEMICOLON = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<TYPE>",
    "<NAME>",
    "\";\"",
  };

}
