/* Generated By:JavaCC: Do not edit this line. RuleParserDefaultVisitor.java Version 7.0.13 */
package io.leaderli.rule.tree;

public class RuleParserDefaultVisitor implements RuleParserVisitor {
    public void defaultVisit(SimpleNode node, StringBuilder data) {
        node.childrenAccept(this, data);
        return;
    }

    public void visit(SimpleNode node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTStart node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTrule node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTand node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTor node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTterm node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTneg node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTnum node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTstr node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTcompare2 node, StringBuilder data) {
        defaultVisit(node, data);
    }

    public void visit(ASTtest node, StringBuilder data) {
        defaultVisit(node, data);
    }
}
/* JavaCC - OriginalChecksum=3300b358d5f66e84f3f207d4791e5004 (do not edit this line) */
