/* Generated By:JJTree&JavaCC: Do not edit this line. RuleParserConstants.java */
package io.leaderli.rule.tree;

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RuleParserConstants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int TYPE = 2;
    /** RegularExpression Id. */
    int NAME = 3;
    /** RegularExpression Id. */
    int NUM = 4;
    /** RegularExpression Id. */
    int INT = 5;
    /** RegularExpression Id. */
    int FLOAT = 6;
    /** RegularExpression Id. */
    int SEMICOLON = 7;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = { "<EOF>", "\" \"", "<TYPE>", "<NAME>", "<NUM>", "<INT>", "<FLOAT>", "\";\"", };

}
